### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by danilacasito** [ov3rwrite/OC-Discord#1]
this don't work with my python and my oc

**Comment by ov3rwrite** [comment]
Did you open your port that you are using?What error do you have when you run the code?

**Comment by danilacasito** [comment]
I put the port on 1334 in the two files and put my local ip address, I run first the py file, and it simply waits, nothing output, but when I execute the lua program, the py file doesn't output the connected message, and I execute the /execute_lua ls there appear an error

**Comment by ov3rwrite** [comment]
You shouldn't put your local ip adress(like 127.0.0.1 for example), you should put your real ip adress instead.
